#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBConstancias")]
	public partial class DataClasses1ConstanciasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertConstancia(Constancia instance);
    partial void UpdateConstancia(Constancia instance);
    partial void DeleteConstancia(Constancia instance);
    partial void InsertConstanciaImparticion(ConstanciaImparticion instance);
    partial void UpdateConstanciaImparticion(ConstanciaImparticion instance);
    partial void DeleteConstanciaImparticion(ConstanciaImparticion instance);
    partial void InsertConstanciaJurado(ConstanciaJurado instance);
    partial void UpdateConstanciaJurado(ConstanciaJurado instance);
    partial void DeleteConstanciaJurado(ConstanciaJurado instance);
    partial void InsertConstanciaPLADEA(ConstanciaPLADEA instance);
    partial void UpdateConstanciaPLADEA(ConstanciaPLADEA instance);
    partial void DeleteConstanciaPLADEA(ConstanciaPLADEA instance);
    partial void InsertConstanciaProyecto(ConstanciaProyecto instance);
    partial void UpdateConstanciaProyecto(ConstanciaProyecto instance);
    partial void DeleteConstanciaProyecto(ConstanciaProyecto instance);
    partial void InsertFirmaElectronica(FirmaElectronica instance);
    partial void UpdateFirmaElectronica(FirmaElectronica instance);
    partial void DeleteFirmaElectronica(FirmaElectronica instance);
    partial void InsertPersonalAdministrativo(PersonalAdministrativo instance);
    partial void UpdatePersonalAdministrativo(PersonalAdministrativo instance);
    partial void DeletePersonalAdministrativo(PersonalAdministrativo instance);
    partial void InsertProfesor(Profesor instance);
    partial void UpdateProfesor(Profesor instance);
    partial void DeleteProfesor(Profesor instance);
    #endregion
		
		public DataClasses1ConstanciasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1ConstanciasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1ConstanciasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1ConstanciasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Constancia> Constancia
		{
			get
			{
				return this.GetTable<Constancia>();
			}
		}
		
		public System.Data.Linq.Table<ConstanciaImparticion> ConstanciaImparticion
		{
			get
			{
				return this.GetTable<ConstanciaImparticion>();
			}
		}
		
		public System.Data.Linq.Table<ConstanciaJurado> ConstanciaJurado
		{
			get
			{
				return this.GetTable<ConstanciaJurado>();
			}
		}
		
		public System.Data.Linq.Table<ConstanciaPLADEA> ConstanciaPLADEA
		{
			get
			{
				return this.GetTable<ConstanciaPLADEA>();
			}
		}
		
		public System.Data.Linq.Table<ConstanciaProyecto> ConstanciaProyecto
		{
			get
			{
				return this.GetTable<ConstanciaProyecto>();
			}
		}
		
		public System.Data.Linq.Table<FirmaElectronica> FirmaElectronica
		{
			get
			{
				return this.GetTable<FirmaElectronica>();
			}
		}
		
		public System.Data.Linq.Table<PersonalAdministrativo> PersonalAdministrativo
		{
			get
			{
				return this.GetTable<PersonalAdministrativo>();
			}
		}
		
		public System.Data.Linq.Table<Profesor> Profesor
		{
			get
			{
				return this.GetTable<Profesor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Constancia")]
	public partial class Constancia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Constancia;
		
		private System.DateTime _fechaCreacionConstancia;
		
		private int _FK_id_Profesor;
		
		private int _FK_Id_Firma;
		
		private EntitySet<ConstanciaImparticion> _ConstanciaImparticion;
		
		private EntitySet<ConstanciaJurado> _ConstanciaJurado;
		
		private EntitySet<ConstanciaPLADEA> _ConstanciaPLADEA;
		
		private EntitySet<ConstanciaProyecto> _ConstanciaProyecto;
		
		private EntityRef<FirmaElectronica> _FirmaElectronica;
		
		private EntityRef<Profesor> _Profesor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_ConstanciaChanging(int value);
    partial void OnId_ConstanciaChanged();
    partial void OnfechaCreacionConstanciaChanging(System.DateTime value);
    partial void OnfechaCreacionConstanciaChanged();
    partial void OnFK_id_ProfesorChanging(int value);
    partial void OnFK_id_ProfesorChanged();
    partial void OnFK_Id_FirmaChanging(int value);
    partial void OnFK_Id_FirmaChanged();
    #endregion
		
		public Constancia()
		{
			this._ConstanciaImparticion = new EntitySet<ConstanciaImparticion>(new Action<ConstanciaImparticion>(this.attach_ConstanciaImparticion), new Action<ConstanciaImparticion>(this.detach_ConstanciaImparticion));
			this._ConstanciaJurado = new EntitySet<ConstanciaJurado>(new Action<ConstanciaJurado>(this.attach_ConstanciaJurado), new Action<ConstanciaJurado>(this.detach_ConstanciaJurado));
			this._ConstanciaPLADEA = new EntitySet<ConstanciaPLADEA>(new Action<ConstanciaPLADEA>(this.attach_ConstanciaPLADEA), new Action<ConstanciaPLADEA>(this.detach_ConstanciaPLADEA));
			this._ConstanciaProyecto = new EntitySet<ConstanciaProyecto>(new Action<ConstanciaProyecto>(this.attach_ConstanciaProyecto), new Action<ConstanciaProyecto>(this.detach_ConstanciaProyecto));
			this._FirmaElectronica = default(EntityRef<FirmaElectronica>);
			this._Profesor = default(EntityRef<Profesor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Constancia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Constancia
		{
			get
			{
				return this._Id_Constancia;
			}
			set
			{
				if ((this._Id_Constancia != value))
				{
					this.OnId_ConstanciaChanging(value);
					this.SendPropertyChanging();
					this._Id_Constancia = value;
					this.SendPropertyChanged("Id_Constancia");
					this.OnId_ConstanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacionConstancia", DbType="Date NOT NULL")]
		public System.DateTime fechaCreacionConstancia
		{
			get
			{
				return this._fechaCreacionConstancia;
			}
			set
			{
				if ((this._fechaCreacionConstancia != value))
				{
					this.OnfechaCreacionConstanciaChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacionConstancia = value;
					this.SendPropertyChanged("fechaCreacionConstancia");
					this.OnfechaCreacionConstanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_id_Profesor", DbType="Int NOT NULL")]
		public int FK_id_Profesor
		{
			get
			{
				return this._FK_id_Profesor;
			}
			set
			{
				if ((this._FK_id_Profesor != value))
				{
					if (this._Profesor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_id_ProfesorChanging(value);
					this.SendPropertyChanging();
					this._FK_id_Profesor = value;
					this.SendPropertyChanged("FK_id_Profesor");
					this.OnFK_id_ProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Id_Firma", DbType="Int NOT NULL")]
		public int FK_Id_Firma
		{
			get
			{
				return this._FK_Id_Firma;
			}
			set
			{
				if ((this._FK_Id_Firma != value))
				{
					if (this._FirmaElectronica.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Id_FirmaChanging(value);
					this.SendPropertyChanging();
					this._FK_Id_Firma = value;
					this.SendPropertyChanged("FK_Id_Firma");
					this.OnFK_Id_FirmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaImparticion", Storage="_ConstanciaImparticion", ThisKey="Id_Constancia", OtherKey="FK_Id_constancia")]
		public EntitySet<ConstanciaImparticion> ConstanciaImparticion
		{
			get
			{
				return this._ConstanciaImparticion;
			}
			set
			{
				this._ConstanciaImparticion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaJurado", Storage="_ConstanciaJurado", ThisKey="Id_Constancia", OtherKey="FK_Id_constancia")]
		public EntitySet<ConstanciaJurado> ConstanciaJurado
		{
			get
			{
				return this._ConstanciaJurado;
			}
			set
			{
				this._ConstanciaJurado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaPLADEA", Storage="_ConstanciaPLADEA", ThisKey="Id_Constancia", OtherKey="FK_Id_constancia")]
		public EntitySet<ConstanciaPLADEA> ConstanciaPLADEA
		{
			get
			{
				return this._ConstanciaPLADEA;
			}
			set
			{
				this._ConstanciaPLADEA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaProyecto", Storage="_ConstanciaProyecto", ThisKey="Id_Constancia", OtherKey="FK_Id_constancia")]
		public EntitySet<ConstanciaProyecto> ConstanciaProyecto
		{
			get
			{
				return this._ConstanciaProyecto;
			}
			set
			{
				this._ConstanciaProyecto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FirmaElectronica_Constancia", Storage="_FirmaElectronica", ThisKey="FK_Id_Firma", OtherKey="Id_firma", IsForeignKey=true)]
		public FirmaElectronica FirmaElectronica
		{
			get
			{
				return this._FirmaElectronica.Entity;
			}
			set
			{
				FirmaElectronica previousValue = this._FirmaElectronica.Entity;
				if (((previousValue != value) 
							|| (this._FirmaElectronica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._FirmaElectronica.Entity = null;
						previousValue.Constancia.Remove(this);
					}
					this._FirmaElectronica.Entity = value;
					if ((value != null))
					{
						value.Constancia.Add(this);
						this._FK_Id_Firma = value.Id_firma;
					}
					else
					{
						this._FK_Id_Firma = default(int);
					}
					this.SendPropertyChanged("FirmaElectronica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Constancia", Storage="_Profesor", ThisKey="FK_id_Profesor", OtherKey="Id_profesor", IsForeignKey=true)]
		public Profesor Profesor
		{
			get
			{
				return this._Profesor.Entity;
			}
			set
			{
				Profesor previousValue = this._Profesor.Entity;
				if (((previousValue != value) 
							|| (this._Profesor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Profesor.Entity = null;
						previousValue.Constancia.Remove(this);
					}
					this._Profesor.Entity = value;
					if ((value != null))
					{
						value.Constancia.Add(this);
						this._FK_id_Profesor = value.Id_profesor;
					}
					else
					{
						this._FK_id_Profesor = default(int);
					}
					this.SendPropertyChanged("Profesor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ConstanciaImparticion(ConstanciaImparticion entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = this;
		}
		
		private void detach_ConstanciaImparticion(ConstanciaImparticion entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = null;
		}
		
		private void attach_ConstanciaJurado(ConstanciaJurado entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = this;
		}
		
		private void detach_ConstanciaJurado(ConstanciaJurado entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = null;
		}
		
		private void attach_ConstanciaPLADEA(ConstanciaPLADEA entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = this;
		}
		
		private void detach_ConstanciaPLADEA(ConstanciaPLADEA entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = null;
		}
		
		private void attach_ConstanciaProyecto(ConstanciaProyecto entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = this;
		}
		
		private void detach_ConstanciaProyecto(ConstanciaProyecto entity)
		{
			this.SendPropertyChanging();
			entity.Constancia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConstanciaImparticion")]
	public partial class ConstanciaImparticion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_constanciaImparticion;
		
		private string _bloque;
		
		private string _credito;
		
		private string _esperienciaEducativa;
		
		private System.TimeSpan _hora;
		
		private System.DateTime _mes;
		
		private string _prograamaEducativo;
		
		private string _seccion;
		
		private string _semana;
		
		private int _FK_Id_constancia;
		
		private EntityRef<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_constanciaImparticionChanging(int value);
    partial void OnId_constanciaImparticionChanged();
    partial void OnbloqueChanging(string value);
    partial void OnbloqueChanged();
    partial void OncreditoChanging(string value);
    partial void OncreditoChanged();
    partial void OnesperienciaEducativaChanging(string value);
    partial void OnesperienciaEducativaChanged();
    partial void OnhoraChanging(System.TimeSpan value);
    partial void OnhoraChanged();
    partial void OnmesChanging(System.DateTime value);
    partial void OnmesChanged();
    partial void OnprograamaEducativoChanging(string value);
    partial void OnprograamaEducativoChanged();
    partial void OnseccionChanging(string value);
    partial void OnseccionChanged();
    partial void OnsemanaChanging(string value);
    partial void OnsemanaChanged();
    partial void OnFK_Id_constanciaChanging(int value);
    partial void OnFK_Id_constanciaChanged();
    #endregion
		
		public ConstanciaImparticion()
		{
			this._Constancia = default(EntityRef<Constancia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_constanciaImparticion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_constanciaImparticion
		{
			get
			{
				return this._Id_constanciaImparticion;
			}
			set
			{
				if ((this._Id_constanciaImparticion != value))
				{
					this.OnId_constanciaImparticionChanging(value);
					this.SendPropertyChanging();
					this._Id_constanciaImparticion = value;
					this.SendPropertyChanged("Id_constanciaImparticion");
					this.OnId_constanciaImparticionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloque", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string bloque
		{
			get
			{
				return this._bloque;
			}
			set
			{
				if ((this._bloque != value))
				{
					this.OnbloqueChanging(value);
					this.SendPropertyChanging();
					this._bloque = value;
					this.SendPropertyChanged("bloque");
					this.OnbloqueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credito", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string credito
		{
			get
			{
				return this._credito;
			}
			set
			{
				if ((this._credito != value))
				{
					this.OncreditoChanging(value);
					this.SendPropertyChanging();
					this._credito = value;
					this.SendPropertyChanged("credito");
					this.OncreditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_esperienciaEducativa", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string esperienciaEducativa
		{
			get
			{
				return this._esperienciaEducativa;
			}
			set
			{
				if ((this._esperienciaEducativa != value))
				{
					this.OnesperienciaEducativaChanging(value);
					this.SendPropertyChanging();
					this._esperienciaEducativa = value;
					this.SendPropertyChanged("esperienciaEducativa");
					this.OnesperienciaEducativaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mes", DbType="Date NOT NULL")]
		public System.DateTime mes
		{
			get
			{
				return this._mes;
			}
			set
			{
				if ((this._mes != value))
				{
					this.OnmesChanging(value);
					this.SendPropertyChanging();
					this._mes = value;
					this.SendPropertyChanged("mes");
					this.OnmesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prograamaEducativo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string prograamaEducativo
		{
			get
			{
				return this._prograamaEducativo;
			}
			set
			{
				if ((this._prograamaEducativo != value))
				{
					this.OnprograamaEducativoChanging(value);
					this.SendPropertyChanging();
					this._prograamaEducativo = value;
					this.SendPropertyChanged("prograamaEducativo");
					this.OnprograamaEducativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seccion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string seccion
		{
			get
			{
				return this._seccion;
			}
			set
			{
				if ((this._seccion != value))
				{
					this.OnseccionChanging(value);
					this.SendPropertyChanging();
					this._seccion = value;
					this.SendPropertyChanged("seccion");
					this.OnseccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_semana", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string semana
		{
			get
			{
				return this._semana;
			}
			set
			{
				if ((this._semana != value))
				{
					this.OnsemanaChanging(value);
					this.SendPropertyChanging();
					this._semana = value;
					this.SendPropertyChanged("semana");
					this.OnsemanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Id_constancia", DbType="Int NOT NULL")]
		public int FK_Id_constancia
		{
			get
			{
				return this._FK_Id_constancia;
			}
			set
			{
				if ((this._FK_Id_constancia != value))
				{
					if (this._Constancia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Id_constanciaChanging(value);
					this.SendPropertyChanging();
					this._FK_Id_constancia = value;
					this.SendPropertyChanged("FK_Id_constancia");
					this.OnFK_Id_constanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaImparticion", Storage="_Constancia", ThisKey="FK_Id_constancia", OtherKey="Id_Constancia", IsForeignKey=true)]
		public Constancia Constancia
		{
			get
			{
				return this._Constancia.Entity;
			}
			set
			{
				Constancia previousValue = this._Constancia.Entity;
				if (((previousValue != value) 
							|| (this._Constancia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Constancia.Entity = null;
						previousValue.ConstanciaImparticion.Remove(this);
					}
					this._Constancia.Entity = value;
					if ((value != null))
					{
						value.ConstanciaImparticion.Add(this);
						this._FK_Id_constancia = value.Id_Constancia;
					}
					else
					{
						this._FK_Id_constancia = default(int);
					}
					this.SendPropertyChanged("Constancia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConstanciaJurado")]
	public partial class ConstanciaJurado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_constanciaJurado;
		
		private System.DateTime _fechaPresentacion;
		
		private string _modalidad;
		
		private string _nombreAlumno;
		
		private string _nombreProyecto;
		
		private string _resultado;
		
		private string _Cargo;
		
		private string _Licenciatura;
		
		private int _FK_Id_constancia;
		
		private EntityRef<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_constanciaJuradoChanging(int value);
    partial void OnId_constanciaJuradoChanged();
    partial void OnfechaPresentacionChanging(System.DateTime value);
    partial void OnfechaPresentacionChanged();
    partial void OnmodalidadChanging(string value);
    partial void OnmodalidadChanged();
    partial void OnnombreAlumnoChanging(string value);
    partial void OnnombreAlumnoChanged();
    partial void OnnombreProyectoChanging(string value);
    partial void OnnombreProyectoChanged();
    partial void OnresultadoChanging(string value);
    partial void OnresultadoChanged();
    partial void OnCargoChanging(string value);
    partial void OnCargoChanged();
    partial void OnLicenciaturaChanging(string value);
    partial void OnLicenciaturaChanged();
    partial void OnFK_Id_constanciaChanging(int value);
    partial void OnFK_Id_constanciaChanged();
    #endregion
		
		public ConstanciaJurado()
		{
			this._Constancia = default(EntityRef<Constancia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_constanciaJurado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_constanciaJurado
		{
			get
			{
				return this._Id_constanciaJurado;
			}
			set
			{
				if ((this._Id_constanciaJurado != value))
				{
					this.OnId_constanciaJuradoChanging(value);
					this.SendPropertyChanging();
					this._Id_constanciaJurado = value;
					this.SendPropertyChanged("Id_constanciaJurado");
					this.OnId_constanciaJuradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaPresentacion", DbType="Date NOT NULL")]
		public System.DateTime fechaPresentacion
		{
			get
			{
				return this._fechaPresentacion;
			}
			set
			{
				if ((this._fechaPresentacion != value))
				{
					this.OnfechaPresentacionChanging(value);
					this.SendPropertyChanging();
					this._fechaPresentacion = value;
					this.SendPropertyChanged("fechaPresentacion");
					this.OnfechaPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modalidad", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string modalidad
		{
			get
			{
				return this._modalidad;
			}
			set
			{
				if ((this._modalidad != value))
				{
					this.OnmodalidadChanging(value);
					this.SendPropertyChanging();
					this._modalidad = value;
					this.SendPropertyChanged("modalidad");
					this.OnmodalidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreAlumno", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreAlumno
		{
			get
			{
				return this._nombreAlumno;
			}
			set
			{
				if ((this._nombreAlumno != value))
				{
					this.OnnombreAlumnoChanging(value);
					this.SendPropertyChanging();
					this._nombreAlumno = value;
					this.SendPropertyChanged("nombreAlumno");
					this.OnnombreAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreProyecto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreProyecto
		{
			get
			{
				return this._nombreProyecto;
			}
			set
			{
				if ((this._nombreProyecto != value))
				{
					this.OnnombreProyectoChanging(value);
					this.SendPropertyChanging();
					this._nombreProyecto = value;
					this.SendPropertyChanged("nombreProyecto");
					this.OnnombreProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string resultado
		{
			get
			{
				return this._resultado;
			}
			set
			{
				if ((this._resultado != value))
				{
					this.OnresultadoChanging(value);
					this.SendPropertyChanging();
					this._resultado = value;
					this.SendPropertyChanged("resultado");
					this.OnresultadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this.OnCargoChanging(value);
					this.SendPropertyChanging();
					this._Cargo = value;
					this.SendPropertyChanged("Cargo");
					this.OnCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Licenciatura", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Licenciatura
		{
			get
			{
				return this._Licenciatura;
			}
			set
			{
				if ((this._Licenciatura != value))
				{
					this.OnLicenciaturaChanging(value);
					this.SendPropertyChanging();
					this._Licenciatura = value;
					this.SendPropertyChanged("Licenciatura");
					this.OnLicenciaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Id_constancia", DbType="Int NOT NULL")]
		public int FK_Id_constancia
		{
			get
			{
				return this._FK_Id_constancia;
			}
			set
			{
				if ((this._FK_Id_constancia != value))
				{
					if (this._Constancia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Id_constanciaChanging(value);
					this.SendPropertyChanging();
					this._FK_Id_constancia = value;
					this.SendPropertyChanged("FK_Id_constancia");
					this.OnFK_Id_constanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaJurado", Storage="_Constancia", ThisKey="FK_Id_constancia", OtherKey="Id_Constancia", IsForeignKey=true)]
		public Constancia Constancia
		{
			get
			{
				return this._Constancia.Entity;
			}
			set
			{
				Constancia previousValue = this._Constancia.Entity;
				if (((previousValue != value) 
							|| (this._Constancia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Constancia.Entity = null;
						previousValue.ConstanciaJurado.Remove(this);
					}
					this._Constancia.Entity = value;
					if ((value != null))
					{
						value.ConstanciaJurado.Add(this);
						this._FK_Id_constancia = value.Id_Constancia;
					}
					else
					{
						this._FK_Id_constancia = default(int);
					}
					this.SendPropertyChanged("Constancia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConstanciaPLADEA")]
	public partial class ConstanciaPLADEA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_constanciaPLADEA;
		
		private string _acciones;
		
		private string _ejeEstrategico;
		
		private string _metas;
		
		private string _objetivosGenerales;
		
		private string _programaEstrategico;
		
		private int _FK_Id_constancia;
		
		private EntityRef<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_constanciaPLADEAChanging(int value);
    partial void OnId_constanciaPLADEAChanged();
    partial void OnaccionesChanging(string value);
    partial void OnaccionesChanged();
    partial void OnejeEstrategicoChanging(string value);
    partial void OnejeEstrategicoChanged();
    partial void OnmetasChanging(string value);
    partial void OnmetasChanged();
    partial void OnobjetivosGeneralesChanging(string value);
    partial void OnobjetivosGeneralesChanged();
    partial void OnprogramaEstrategicoChanging(string value);
    partial void OnprogramaEstrategicoChanged();
    partial void OnFK_Id_constanciaChanging(int value);
    partial void OnFK_Id_constanciaChanged();
    #endregion
		
		public ConstanciaPLADEA()
		{
			this._Constancia = default(EntityRef<Constancia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_constanciaPLADEA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_constanciaPLADEA
		{
			get
			{
				return this._Id_constanciaPLADEA;
			}
			set
			{
				if ((this._Id_constanciaPLADEA != value))
				{
					this.OnId_constanciaPLADEAChanging(value);
					this.SendPropertyChanging();
					this._Id_constanciaPLADEA = value;
					this.SendPropertyChanged("Id_constanciaPLADEA");
					this.OnId_constanciaPLADEAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acciones", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string acciones
		{
			get
			{
				return this._acciones;
			}
			set
			{
				if ((this._acciones != value))
				{
					this.OnaccionesChanging(value);
					this.SendPropertyChanging();
					this._acciones = value;
					this.SendPropertyChanged("acciones");
					this.OnaccionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ejeEstrategico", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ejeEstrategico
		{
			get
			{
				return this._ejeEstrategico;
			}
			set
			{
				if ((this._ejeEstrategico != value))
				{
					this.OnejeEstrategicoChanging(value);
					this.SendPropertyChanging();
					this._ejeEstrategico = value;
					this.SendPropertyChanged("ejeEstrategico");
					this.OnejeEstrategicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metas", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string metas
		{
			get
			{
				return this._metas;
			}
			set
			{
				if ((this._metas != value))
				{
					this.OnmetasChanging(value);
					this.SendPropertyChanging();
					this._metas = value;
					this.SendPropertyChanged("metas");
					this.OnmetasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objetivosGenerales", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string objetivosGenerales
		{
			get
			{
				return this._objetivosGenerales;
			}
			set
			{
				if ((this._objetivosGenerales != value))
				{
					this.OnobjetivosGeneralesChanging(value);
					this.SendPropertyChanging();
					this._objetivosGenerales = value;
					this.SendPropertyChanged("objetivosGenerales");
					this.OnobjetivosGeneralesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programaEstrategico", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string programaEstrategico
		{
			get
			{
				return this._programaEstrategico;
			}
			set
			{
				if ((this._programaEstrategico != value))
				{
					this.OnprogramaEstrategicoChanging(value);
					this.SendPropertyChanging();
					this._programaEstrategico = value;
					this.SendPropertyChanged("programaEstrategico");
					this.OnprogramaEstrategicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Id_constancia", DbType="Int NOT NULL")]
		public int FK_Id_constancia
		{
			get
			{
				return this._FK_Id_constancia;
			}
			set
			{
				if ((this._FK_Id_constancia != value))
				{
					if (this._Constancia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Id_constanciaChanging(value);
					this.SendPropertyChanging();
					this._FK_Id_constancia = value;
					this.SendPropertyChanged("FK_Id_constancia");
					this.OnFK_Id_constanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaPLADEA", Storage="_Constancia", ThisKey="FK_Id_constancia", OtherKey="Id_Constancia", IsForeignKey=true)]
		public Constancia Constancia
		{
			get
			{
				return this._Constancia.Entity;
			}
			set
			{
				Constancia previousValue = this._Constancia.Entity;
				if (((previousValue != value) 
							|| (this._Constancia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Constancia.Entity = null;
						previousValue.ConstanciaPLADEA.Remove(this);
					}
					this._Constancia.Entity = value;
					if ((value != null))
					{
						value.ConstanciaPLADEA.Add(this);
						this._FK_Id_constancia = value.Id_Constancia;
					}
					else
					{
						this._FK_Id_constancia = default(int);
					}
					this.SendPropertyChanged("Constancia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ConstanciaProyecto")]
	public partial class ConstanciaProyecto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_constanciaProyecto;
		
		private string _duracion;
		
		private string _impactoObtenido;
		
		private string _lugarDesarrollo;
		
		private string _nombreAlumno;
		
		private string _proyectoRealizado;
		
		private int _FK_Id_constancia;
		
		private EntityRef<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_constanciaProyectoChanging(int value);
    partial void OnId_constanciaProyectoChanged();
    partial void OnduracionChanging(string value);
    partial void OnduracionChanged();
    partial void OnimpactoObtenidoChanging(string value);
    partial void OnimpactoObtenidoChanged();
    partial void OnlugarDesarrolloChanging(string value);
    partial void OnlugarDesarrolloChanged();
    partial void OnnombreAlumnoChanging(string value);
    partial void OnnombreAlumnoChanged();
    partial void OnproyectoRealizadoChanging(string value);
    partial void OnproyectoRealizadoChanged();
    partial void OnFK_Id_constanciaChanging(int value);
    partial void OnFK_Id_constanciaChanged();
    #endregion
		
		public ConstanciaProyecto()
		{
			this._Constancia = default(EntityRef<Constancia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_constanciaProyecto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_constanciaProyecto
		{
			get
			{
				return this._Id_constanciaProyecto;
			}
			set
			{
				if ((this._Id_constanciaProyecto != value))
				{
					this.OnId_constanciaProyectoChanging(value);
					this.SendPropertyChanging();
					this._Id_constanciaProyecto = value;
					this.SendPropertyChanged("Id_constanciaProyecto");
					this.OnId_constanciaProyectoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impactoObtenido", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string impactoObtenido
		{
			get
			{
				return this._impactoObtenido;
			}
			set
			{
				if ((this._impactoObtenido != value))
				{
					this.OnimpactoObtenidoChanging(value);
					this.SendPropertyChanging();
					this._impactoObtenido = value;
					this.SendPropertyChanged("impactoObtenido");
					this.OnimpactoObtenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugarDesarrollo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string lugarDesarrollo
		{
			get
			{
				return this._lugarDesarrollo;
			}
			set
			{
				if ((this._lugarDesarrollo != value))
				{
					this.OnlugarDesarrolloChanging(value);
					this.SendPropertyChanging();
					this._lugarDesarrollo = value;
					this.SendPropertyChanged("lugarDesarrollo");
					this.OnlugarDesarrolloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreAlumno", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreAlumno
		{
			get
			{
				return this._nombreAlumno;
			}
			set
			{
				if ((this._nombreAlumno != value))
				{
					this.OnnombreAlumnoChanging(value);
					this.SendPropertyChanging();
					this._nombreAlumno = value;
					this.SendPropertyChanged("nombreAlumno");
					this.OnnombreAlumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proyectoRealizado", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string proyectoRealizado
		{
			get
			{
				return this._proyectoRealizado;
			}
			set
			{
				if ((this._proyectoRealizado != value))
				{
					this.OnproyectoRealizadoChanging(value);
					this.SendPropertyChanging();
					this._proyectoRealizado = value;
					this.SendPropertyChanged("proyectoRealizado");
					this.OnproyectoRealizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Id_constancia", DbType="Int NOT NULL")]
		public int FK_Id_constancia
		{
			get
			{
				return this._FK_Id_constancia;
			}
			set
			{
				if ((this._FK_Id_constancia != value))
				{
					if (this._Constancia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Id_constanciaChanging(value);
					this.SendPropertyChanging();
					this._FK_Id_constancia = value;
					this.SendPropertyChanged("FK_Id_constancia");
					this.OnFK_Id_constanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Constancia_ConstanciaProyecto", Storage="_Constancia", ThisKey="FK_Id_constancia", OtherKey="Id_Constancia", IsForeignKey=true)]
		public Constancia Constancia
		{
			get
			{
				return this._Constancia.Entity;
			}
			set
			{
				Constancia previousValue = this._Constancia.Entity;
				if (((previousValue != value) 
							|| (this._Constancia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Constancia.Entity = null;
						previousValue.ConstanciaProyecto.Remove(this);
					}
					this._Constancia.Entity = value;
					if ((value != null))
					{
						value.ConstanciaProyecto.Add(this);
						this._FK_Id_constancia = value.Id_Constancia;
					}
					else
					{
						this._FK_Id_constancia = default(int);
					}
					this.SendPropertyChanged("Constancia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FirmaElectronica")]
	public partial class FirmaElectronica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_firma;
		
		private string _clave;
		
		private System.DateTime _fechaCreacion;
		
		private System.DateTime _fechaExpiracion;
		
		private EntitySet<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_firmaChanging(int value);
    partial void OnId_firmaChanged();
    partial void OnclaveChanging(string value);
    partial void OnclaveChanged();
    partial void OnfechaCreacionChanging(System.DateTime value);
    partial void OnfechaCreacionChanged();
    partial void OnfechaExpiracionChanging(System.DateTime value);
    partial void OnfechaExpiracionChanged();
    #endregion
		
		public FirmaElectronica()
		{
			this._Constancia = new EntitySet<Constancia>(new Action<Constancia>(this.attach_Constancia), new Action<Constancia>(this.detach_Constancia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_firma", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_firma
		{
			get
			{
				return this._Id_firma;
			}
			set
			{
				if ((this._Id_firma != value))
				{
					this.OnId_firmaChanging(value);
					this.SendPropertyChanging();
					this._Id_firma = value;
					this.SendPropertyChanged("Id_firma");
					this.OnId_firmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clave", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string clave
		{
			get
			{
				return this._clave;
			}
			set
			{
				if ((this._clave != value))
				{
					this.OnclaveChanging(value);
					this.SendPropertyChanging();
					this._clave = value;
					this.SendPropertyChanged("clave");
					this.OnclaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime fechaCreacion
		{
			get
			{
				return this._fechaCreacion;
			}
			set
			{
				if ((this._fechaCreacion != value))
				{
					this.OnfechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._fechaCreacion = value;
					this.SendPropertyChanged("fechaCreacion");
					this.OnfechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaExpiracion", DbType="Date NOT NULL")]
		public System.DateTime fechaExpiracion
		{
			get
			{
				return this._fechaExpiracion;
			}
			set
			{
				if ((this._fechaExpiracion != value))
				{
					this.OnfechaExpiracionChanging(value);
					this.SendPropertyChanging();
					this._fechaExpiracion = value;
					this.SendPropertyChanged("fechaExpiracion");
					this.OnfechaExpiracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="FirmaElectronica_Constancia", Storage="_Constancia", ThisKey="Id_firma", OtherKey="FK_Id_Firma")]
		public EntitySet<Constancia> Constancia
		{
			get
			{
				return this._Constancia;
			}
			set
			{
				this._Constancia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Constancia(Constancia entity)
		{
			this.SendPropertyChanging();
			entity.FirmaElectronica = this;
		}
		
		private void detach_Constancia(Constancia entity)
		{
			this.SendPropertyChanging();
			entity.FirmaElectronica = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PersonalAdministrativo")]
	public partial class PersonalAdministrativo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_personalAdministrativo;
		
		private string _nombreCompleto;
		
		private string _password;
		
		private string _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_personalAdministrativoChanging(int value);
    partial void OnId_personalAdministrativoChanged();
    partial void OnnombreCompletoChanging(string value);
    partial void OnnombreCompletoChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    #endregion
		
		public PersonalAdministrativo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_personalAdministrativo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_personalAdministrativo
		{
			get
			{
				return this._Id_personalAdministrativo;
			}
			set
			{
				if ((this._Id_personalAdministrativo != value))
				{
					this.OnId_personalAdministrativoChanging(value);
					this.SendPropertyChanging();
					this._Id_personalAdministrativo = value;
					this.SendPropertyChanged("Id_personalAdministrativo");
					this.OnId_personalAdministrativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCompleto", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombreCompleto
		{
			get
			{
				return this._nombreCompleto;
			}
			set
			{
				if ((this._nombreCompleto != value))
				{
					this.OnnombreCompletoChanging(value);
					this.SendPropertyChanging();
					this._nombreCompleto = value;
					this.SendPropertyChanged("nombreCompleto");
					this.OnnombreCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Profesor")]
	public partial class Profesor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_profesor;
		
		private string _nombreCompleto;
		
		private string _numeroPersonal;
		
		private EntitySet<Constancia> _Constancia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_profesorChanging(int value);
    partial void OnId_profesorChanged();
    partial void OnnombreCompletoChanging(string value);
    partial void OnnombreCompletoChanged();
    partial void OnnumeroPersonalChanging(string value);
    partial void OnnumeroPersonalChanged();
    #endregion
		
		public Profesor()
		{
			this._Constancia = new EntitySet<Constancia>(new Action<Constancia>(this.attach_Constancia), new Action<Constancia>(this.detach_Constancia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_profesor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_profesor
		{
			get
			{
				return this._Id_profesor;
			}
			set
			{
				if ((this._Id_profesor != value))
				{
					this.OnId_profesorChanging(value);
					this.SendPropertyChanging();
					this._Id_profesor = value;
					this.SendPropertyChanged("Id_profesor");
					this.OnId_profesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreCompleto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string nombreCompleto
		{
			get
			{
				return this._nombreCompleto;
			}
			set
			{
				if ((this._nombreCompleto != value))
				{
					this.OnnombreCompletoChanging(value);
					this.SendPropertyChanging();
					this._nombreCompleto = value;
					this.SendPropertyChanged("nombreCompleto");
					this.OnnombreCompletoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroPersonal", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string numeroPersonal
		{
			get
			{
				return this._numeroPersonal;
			}
			set
			{
				if ((this._numeroPersonal != value))
				{
					this.OnnumeroPersonalChanging(value);
					this.SendPropertyChanging();
					this._numeroPersonal = value;
					this.SendPropertyChanged("numeroPersonal");
					this.OnnumeroPersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Profesor_Constancia", Storage="_Constancia", ThisKey="Id_profesor", OtherKey="FK_id_Profesor")]
		public EntitySet<Constancia> Constancia
		{
			get
			{
				return this._Constancia;
			}
			set
			{
				this._Constancia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Constancia(Constancia entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = this;
		}
		
		private void detach_Constancia(Constancia entity)
		{
			this.SendPropertyChanging();
			entity.Profesor = null;
		}
	}
}
#pragma warning restore 1591
